# Generated by Django 4.1 on 2023-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('rediness', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='roast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.IntegerField()),
                ('is_strong', models.BooleanField()),
            ],
        ),
    ]
