# Generated by Django 4.1 on 2023-11-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_rename_grains_grain'),
    ]

    operations = [
        migrations.AddField(
            model_name='grain',
            name='region',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
